# Generated by Django 6.1.1 on 2026-09-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('module', 'PV Module'), ('inverter', 'Inverter'), ('structure', 'Mounting Structure'), ('electrical', 'Electrical'), ('cable', 'Cable'), ('earthing', 'Earthing'), ('other', 'Other')], max_length=50)),
                ('make', models.CharField(blank=True, max_length=200)),
                ('specification', models.TextField(blank=True)),
                ('unit', models.CharField(default='Nos', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=18, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_no', models.CharField(max_length=100, unique=True)),
                ('buisness_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(default='On-Grid', max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validity_days', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('specification', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('make', models.CharField(blank=True, max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
        ),
    ]
