# Generated by Django 6.1.1 on 2026-09-23 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sheet_name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.CharField(max_length=50)),
                ('phase', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('make', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('specification', models.TextField(blank=True)),
                ('solar_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.solarpackage')),
            ],
        ),
    ]
