# Generated by Django 6.1.1 on 2026-09-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_solarpackage_solarpackageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('module', 'PV Module'), ('inverter', 'Inverter'), ('structure', 'Mounting Structure'), ('acdb', 'ACDB'), ('dcdb', 'DCDB'), ('ac_wire', 'AC Wire'), ('dc_cable', 'DC Cable'), ('energy_meter', 'Energy Meter'), ('meter_box', 'Meter Box'), ('ug_cable', 'UG Cable'), ('net_meter', 'Net Meter'), ('electrical', 'Electrical'), ('cable', 'Cable'), ('earthing', 'Earthing'), ('other', 'Other')], max_length=50),
        ),
    ]
