# Generated by Django 6.1.1 on 2026-09-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_sheet', models.CharField(max_length=100)),
                ('excel_cell', models.CharField(max_length=50)),
                ('excel_row', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('current_value', models.CharField(blank=True, max_length=500)),
                ('source_range', models.CharField(blank=True, max_length=500)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_rules', to='quotations.solarpackage')),
            ],
            options={
                'ordering': ['package', 'excel_row'],
            },
        ),
    ]
