# Generated by Django 6.1.1 on 2026-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_packageoptionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='calculated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='calculated_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='documentation',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='electrical_work',
            field=models.DecimalField(decimal_places=2, default=9000, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='final_quotation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='kseb_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='margin_factor',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_work',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='suggested_quotation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='transportation_travel',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12),
        ),
    ]
