# Generated by Django 6.1.1 on 2026-09-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotation_calculated_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
    ]
