# Generated by Django 6.1.1 on 2026-09-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_alter_quotation_loading_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='solar_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quotations.solarpackage'),
        ),
    ]
