# Generated by Django 6.1.1 on 2026-09-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotation_solar_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('panel_type', models.CharField(blank=True, max_length=100)),
                ('dcr_status', models.CharField(choices=[('dcr', 'DCR- With Subsidy'), ('non_dcr', 'Non-DCR - Without Subsidy')], max_length=20)),
                ('wattage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rate_per_watt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=2, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', 'dcr_status', 'wattage'],
            },
        ),
    ]
