# Generated by Django 6.1.1 on 2026-09-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_paneloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='panel_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quotations.paneloption'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_total_watt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
