# Generated by Django 6.1.1 on 2026-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_quotation_panel_option_quotation_panel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='panel_dcr_status',
            field=models.CharField(choices=[('dcr', 'DCR'), ('non_dcr', 'Non-DCR')], default='dcr', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phase',
            field=models.CharField(choices=[('single', 'Single Phase'), ('three', 'Three Phase')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_type',
            field=models.CharField(choices=[('roof', 'Roof Mounted'), ('gp', 'GP'), ('gi', 'GI')], default='roof', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_wage_factor',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='system_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='system_type',
            field=models.CharField(choices=[('on_grid', 'On-Grid'), ('off_grid', 'Off-Grid'), ('hybrid', 'Hybrid')], default='on_grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
