# Generated by Django 6.1.1 on 2026-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_structurewagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='ac_wire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='dc_cable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
