# Generated by Django 6.1.1 on 2026-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_quotation_ac_wire_quotation_dc_cable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inverter_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='other_inverter_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='other_inverter_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
