# Generated by Django 6.1.1 on 2026-09-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_product_inverter_capacity_quotation_inverter_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='margin_factor',
            field=models.DecimalField(decimal_places=2, default=85, max_digits=6),
        ),
    ]
