# Generated by Django 6.1.1 on 2026-10-01 08:42

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_alter_quotation_margin_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('per_watt_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('per_feet_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='solarpackage',
            options={'ordering': ['capacity', 'name']},
        ),
        migrations.AlterModelOptions(
            name='solarpackageitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='margin_factor',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='other_inverter_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='other_inverter_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ac_wire_quantity',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='acdb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='component_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='component_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='component_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='dc_cable_quantity',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='dcdb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='earth_quantity',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='earth_rod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='earthing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quotation',
            name='energy_meter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_make',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inverter_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='margin_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=6),
        ),
        migrations.AddField(
            model_name='quotation',
            name='meter_box',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='net_meter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='non_taxable_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_rate_per_watt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='panel_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='structure_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='taxable_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ug_cable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(default='Nos', max_length=50),
        ),
        migrations.AddField(
            model_name='solarpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solarpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solarpackageitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paneloption',
            name='dcr_status',
            field=models.CharField(choices=[('dcr', 'DCR - With Subsidy'), ('non_dcr', 'Non-DCR - Without Subsidy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paneloption',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='ac_wire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='dc_cable',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='documentation',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='electrical_work',
            field=models.DecimalField(decimal_places=2, default=Decimal('9000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='inverter_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='kseb_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='loading_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='panel_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='structure_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='structure_wage_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='structure_work',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='transportation_travel',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='solarpackageitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5),
        ),
    ]
