# Generated by Django 6.1.1 on 2026-10-01 08:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_structuresetting_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarpackageitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12),
        ),
    ]
