# Generated by Django 6.1.1 on 2026-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_alter_solarpackageitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='panel_quantity_manual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
