# Generated by Django 6.1.1 on 2026-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0018_quotation_panel_quantity_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=40)),
                ('ifsc', models.CharField(max_length=20, verbose_name='IFSC')),
                ('bank_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Payment details',
                'verbose_name_plural': 'Payment details',
            },
        ),
    ]
