# Generated by Django 6.1.1 on 2026-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='structure_kw_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
